#!/bin/bash
filename=$(basename -- "$1")
extension="${filename##*.}"
filename="${filename%.*}"
new_file=$(sed "s/\ /_/g" <<< $filename)
touch "/Users/palashahuja/Documents/notes/Paper Notes/${new_file}.md"
echo "# ${filename} $(date +'%d/%m/%Y')" >> "/Users/palashahuja/Documents/notes/Paper Notes/${new_file}.md" 
